name: Run Frontend Tests

on:
  pull_request:
    branches:
      - main
      - master
      - develop
      - staging
  push:
    branches:
      - main
      - master
      - develop
      - staging

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # adjust to your Node version if needed

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
